version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    env_file:
      - ./backend/.env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planner"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - smm-planner-network

  backend:
    build:
      context: ./backend
      dockerfile: ./ops/Dockerfile
    container_name: nest_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    networks:
      - smm-planner-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./ops/Dockerfile
    container_name: next_frontend
    restart: always
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - smm-planner-network

volumes:
  pgdata:

networks:
  smm-planner-network:
    driver: bridge
