import { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { JSX, ReactNode } from "react"

import { AntdRegistry } from "@ant-design/nextjs-registry"
import "@ant-design/v5-patch-for-react-19"

import { Header } from "@/03_widgets/header/ui"

import "./globals.css"
import "react-loading-skeleton/dist/skeleton.css"

export type TMainLayoutProps = Readonly<{
  children: ReactNode
}>

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: TMainLayoutProps): JSX.Element {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AntdRegistry>
          <Header />
          <main style={{ padding: "20px" }}>{children}</main>
        </AntdRegistry>
      </body>
    </html>
  )
}
