import { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { JSX, ReactNode } from "react"

import "./globals.css"
import { Header } from "@/06_shared/ui"

export type TMainLayoutProps = Readonly<{
  children: ReactNode
}>

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: TMainLayoutProps): JSX.Element {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main style={{ padding: "20px" }}>{children}</main>
      </body>
    </html>
  )
}
